apiVersion: v1
kind: Service
metadata:
  name: demo-app-svc
  labels:
    app: demo-app
spec:
  type: LoadBalancer
  selector:
    app:  demo-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
